---
title: "BarriersInterviewAnalysis"
author: "Kyra Gmoser-Daskalakis"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(RColorBrewer)
```

```{r load data}
alltokens <- read.csv("AllTokens.csv", header=TRUE, sep=';')

#separate benefits and barriers
barriers <- alltokens %>% dplyr::filter(, grepl('Barrier', Codes))
```

```{r create barriers}
#split out benefit codes

barriers$spatialorigin <- ifelse(grepl("Proximate", barriers$Codes), 'Proximate', ifelse(grepl("Remote", barriers$Codes), 'Remote', "missing"))

barriers$temporigin <- ifelse(grepl("Contemporary", barriers$Codes), 'Contemporary', ifelse(grepl("Future", barriers$Codes), 'Future', ifelse(grepl("Legacy", barriers$Codes), 'Legacy', "missing")))

barriers$Barrier <- ifelse(grepl("Cognitive", barriers$Codes), 'Cognitive', ifelse(grepl("Informational", barriers$Codes), 'Informational', ifelse(grepl("Institutional", barriers$Codes), 'Institutional', ifelse(grepl("Phys/Enviro", barriers$Codes), 'Phys/Enviro', ifelse(grepl("Resource", barriers$Codes), 'Resource', ifelse(grepl("Social", barriers$Codes), 'Social', "missing"))))))

barriers$SubBarrier <- ifelse(grepl("Motivation", barriers$Codes), 'Motivation', ifelse(grepl("Translation", barriers$Codes), 'Translation', ifelse(grepl("Urgency", barriers$Codes), 'Urgency', ifelse(grepl("Org Structure", barriers$Codes), 'Org Structure', ifelse(grepl("Regulatory", barriers$Codes), 'Regulatory', ifelse(grepl("Funding", barriers$Codes), 'Funding', ifelse(grepl("Staff Resources", barriers$Codes), 'Staff Resources', ifelse(grepl("External Stakeholders", barriers$Codes), 'External Stakeholders', ifelse(grepl("Internal Collaborators", barriers$Codes), 'Internal Collaborators', ifelse(grepl("Built Enviro", barriers$Codes), 'Built Enviro', ifelse(grepl("Ecological", barriers$Codes), 'Ecological', ifelse(grepl("Physical Enviro", barriers$Codes), 'Physical Enviro', ifelse(grepl("Knowledge", barriers$Codes), 'Knowledge', ifelse(grepl("Science", barriers$Codes), 'Science', ifelse(grepl("Staff Info", barriers$Codes), 'Staff Info', "missing")))))))))))))))

#one 'missing' for barrier type since was not selected as physical enviro
barriers$Barrier <- ifelse(grepl("missing", barriers$Barrier), "Phys/Enviro", barriers$Barrier)

#one 'missing' for temporal origins
barriers$temporigin <- ifelse(grepl("missing", barriers$temporigin), "Contemporary", barriers$temporigin)

```

```{r add resp info}
respondents <- read.csv("RespondentDetails.csv", header=TRUE, sep=';')

#merge with interview benefits tokens
barriers <- left_join(barriers, respondents, by="RespID")
```

```{r start summary}

table(barriers$Barrier)

barriercatCT <- as.data.frame(table(barriers$Barrier, barriers$SubBarrier))

barrierlocCT <- as.data.frame(table(barriers$Barrier, barriers$FinRegion))

barrierjobCT <- as.data.frame(table(barriers$Role, barriers$Barrier))

barrierprojCT <- as.data.frame(table(barriers$Project, barriers$Barrier))


table(barriers$Role)
table(respondents$FinRole)

table(barriers$Project)

table(barriers$OrgType)

barriers$barriercount <- 1

respbars <- barriers %>% group_by(RespID) %>% summarise(sum(barriercount))
summary(respbars$`sum(barriercount)`)




```

```{r overall barriers bar chart}

subbarriers <- filter_if(barriercatCT, is.numeric, all_vars((.) !=0))
subbarriers <- rename(subbarriers, SubCategory = Var2)
subbarriers <- rename(subbarriers, Category = Var1)

subbarriers$Subcategory <- ifelse(subbarriers$SubCategory=="Motivation", "(C) Motivation", ifelse(subbarriers$SubCategory=="Translation", "(C) Translation", ifelse(subbarriers$SubCategory=="Urgency", "(C) Urgency", ifelse(subbarriers$SubCategory=="Knowledge", "(Inf) Knowledge", ifelse(subbarriers$SubCategory=="Science", "(Inf) Science", ifelse(subbarriers$SubCategory=="Staff Info", "(Inf) Staff Info", ifelse(subbarriers$SubCategory=="Org Structure", "(Inst) Org Structure", ifelse(subbarriers$SubCategory=="Regulatory", "(Inst) Regulatory", ifelse(subbarriers$SubCategory=="Built Enviro", "(PE) Built Enviro", ifelse(subbarriers$SubCategory=="Ecological", "(PE) Ecological", ifelse(subbarriers$SubCategory=="Physical Enviro", "(PE) Phys Enviro", ifelse(subbarriers$SubCategory=="Funding", "(R) Funding", ifelse(subbarriers$SubCategory=="Internal Collaborators", "(S) Collaboration", ifelse(subbarriers$SubCategory=="External Stakeholders", "(S) Stakeholders", ifelse(subbarriers$SubCategory=="Staff Resources", "(R) Staff Capacity", "Other")))))))))))))))

subbarriers <- subbarriers %>% mutate(Category = fct_relevel(Category, c("Social", "Resource", "Phys/Enviro", "Institutional", "Informational", "Cognitive")))

```

```{r figure}

subbarriers <- subbarriers %>% mutate(Subcategory=factor(Subcategory, c("(S) Stakeholders", "(S) Collaboration", "(R) Funding", "(R) Staff Capacity", "(PE) Phys Enviro", "(PE) Ecological", "(PE) Built Enviro",  "(Inst) Regulatory", "(Inst) Org Structure", "(Inf) Knowledge", "(Inf) Staff Info", "(Inf) Science", "(C) Motivation", "(C) Urgency", "(C) Translation")))
                                  
ggplot(subbarriers, aes(fill=Category, y=Freq, x=Subcategory)) + 
    geom_bar(stat="identity", position="dodge")+ 
  ggtitle("Reported Barriers to Wetland Restoration") +
  xlab("Barrier Subcategory") + ylab("Frequency") + scale_fill_manual(values=c("#5C8C54","#C2B15B","#55514E","#a95c10", "#fff0db", "#55B458"))+ geom_text(aes(label = Freq), size = 3, hjust = 2) + coord_flip() +
  guides(fill=guide_legend(reverse = TRUE))

str(subbarriers)
```

```{r regional barriers}
view(barrierlocCT)

Barriers <- c("Cognitive", "Informational", "Institutional", "Physical/Enviro", "Resources", "Social")
BayCount <- c(39, 49, 92, 121, 84, 83)
DeltaCount <- c(39, 55, 71, 98, 52, 46)

RegBarrierCounts <- cbind(Barriers, BayCount, DeltaCount)

RegBarrierCounts <- as.data.frame(RegBarrierCounts)

rownames(RegBarrierCounts) <- RegBarrierCounts[,1]
RegBarrierCounts <- RegBarrierCounts[, -1]
RegBarrierCounts$BayCount <- as.numeric(RegBarrierCounts$BayCount)

RegBarrierCounts$DeltaCount <- as.numeric(RegBarrierCounts$DeltaCount)

# Perform the Chi-Square Test
chisq.test(RegBarrierCounts)$expected #all cells expected >5
regchi_result <- chisq.test(RegBarrierCounts)
print(regchi_result)

```

```{r project barriers}
barriers$FinProject <- ifelse(barriers$Project=="H"|barriers$Project=="J", "H, J", barriers$Project)
barrproj <- as.data.frame(table(barriers$Barrier, barriers$FinProject))

projbarrs <- read.csv("barriersbyproject.csv", sep=';')
rownames(projbarrs) <- projbarrs[,1]
projbarrs <- projbarrs[,-1]

chisq.test(projbarrs)$expected #expected counts below 5 use fischer's exact test

projfishtest <- fisher.test(projbarrs, simulate.p.value = TRUE)
projfishtest
```

```{r staff barriers}

barrstaff <- as.data.frame(table(barriers$Barrier, barriers$FinRole))
staffbarrs <- read.csv("StaffBarriers.csv", sep=';')

rownames(staffbarrs) <- staffbarrs[,1]
staffbarrs <- staffbarrs[,-1]

chisq.test(staffbarrs)$expected #expected counts above 5

staffchi_result <- chisq.test(staffbarrs)
print(staffchi_result)
```

```{r new barrier codes by region}
table(barriers$spatialorigin)
table(barriers$temporigin)

table(barriers$spatialorigin, barriers$Barrier)
table(barriers$temporigin, barriers$Barrier)


table(barriers$spatialorigin, barriers$FinRegion)
table(barriers$temporigin, barriers$FinRegion)

#Spatial Jurisdictional By Region
SJBarriers <- c("Proximate", "Remote")
BaySJCount <- c(255, 213)
DeltaSJCount <- c(184, 177)
SJBarriers <- cbind(SJBarriers, BaySJCount, DeltaSJCount)

rownames(SJBarriers) <- SJBarriers[,1]
SJBarriers <- SJBarriers[,-1]
SJBarriers <- as.data.frame(SJBarriers)
SJBarriers$BaySJCount <- as.numeric(SJBarriers$BaySJCount)
SJBarriers$DeltaSJCount <- as.numeric(SJBarriers$DeltaSJCount)

chisq.test(SJBarriers)$expected #Per category >5 for expected counts

regSJchi_result <- chisq.test(SJBarriers)
print(regSJchi_result)

#Temporal by Region
TBarriers <- c("Legacy", "Contemporary", "Future")
BayTCount <- c(72, 341, 55)
DeltaTCount <- c(61, 240, 60)
TBarriers <- cbind(TBarriers, BayTCount, DeltaTCount)

rownames(TBarriers) <- TBarriers[,1]
TBarriers <- TBarriers[,-1]
TBarriers <- as.data.frame(TBarriers)
TBarriers$BayTCount <- as.numeric(TBarriers$BayTCount)
TBarriers$DeltaTCount <- as.numeric(TBarriers$DeltaTCount)

chisq.test(TBarriers)$expected #All per category >5 for expected counts

regTchi_result <- chisq.test(TBarriers)
print(regTchi_result)


```

```{r new barrier codes by categories}
SJbarrierCT <- as.data.frame(table(barriers$spatialorigin, barriers$Barrier))
TbarrierCT <- as.data.frame(table(barriers$temporigin, barriers$Barrier))

SJBiesCT <- c("Proximate", "Remote")
SJCogcount <- c(26, 52)
SJInfocount <- c(65, 39)
SJInstcount <- c(35, 128)
SJPhyscount <- c(173, 46)
SJRescount <- c(44, 92)
SJSoccount <- c(96, 33)
SJBiesCT <- cbind(SJBiesCT, SJCogcount, SJInfocount, SJInstcount, SJPhyscount, SJRescount, SJSoccount)
SJBiesCT <- as.data.frame(SJBiesCT)


rownames(SJBiesCT) <- SJBiesCT[,1]
SJBiesCT <- SJBiesCT[,-1]
SJBiesCT$SJCogcount <- as.numeric(SJBiesCT$SJCogcount)
SJBiesCT$SJInfocount <- as.numeric(SJBiesCT$SJInfocount)
SJBiesCT$SJInstcount <- as.numeric(SJBiesCT$SJInstcount)
SJBiesCT$SJPhyscount <- as.numeric(SJBiesCT$SJPhyscount)
SJBiesCT$SJRescount <- as.numeric(SJBiesCT$SJRescount)
SJBiesCT$SJSoccount <- as.numeric(SJBiesCT$SJSoccount)

chisq.test(SJBiesCT)$expected #all cell counts expected >5 
SJbieschi_result <- chisq.test(SJBiesCT)
print(SJbieschi_result)

```

```{r new barrier codes by category pt 2}
TBiesCT <- c("Legacy", "Contemporary", "Future")
TCogcount <- c(12, 56, 10)
TInfocount <- c(16, 81, 7)
TInstcount <- c(43, 116, 4)
TPhyscount <- c(39, 123, 57)
TRescount <- c(8, 96, 32)
TSoccount <- c(15, 109, 5)
TBiesCT <- cbind(TBiesCT, TCogcount, TInfocount, TInstcount, TPhyscount, TRescount, TSoccount)
TBiesCT <- as.data.frame(TBiesCT)


rownames(TBiesCT) <- TBiesCT[,1]
TBiesCT <- TBiesCT[,-1]
TBiesCT$TCogcount <- as.numeric(TBiesCT$TCogcount)
TBiesCT$TInfocount <- as.numeric(TBiesCT$TInfocount)
TBiesCT$TInstcount <- as.numeric(TBiesCT$TInstcount)
TBiesCT$TPhyscount <- as.numeric(TBiesCT$TPhyscount)
TBiesCT$TRescount <- as.numeric(TBiesCT$TRescount)
TBiesCT$TSoccount <- as.numeric(TBiesCT$TSoccount)

chisq.test(TBiesCT)$expected #all cell counts expected >5 

TBieschi_result <- chisq.test(TBiesCT)
print(TBieschi_result)

```

```{r new barriers figures}

SJCat <- c("Proximate", "Remote")
SJFreq <- c(439, 390)
TempCat <- c("Legacy", "Contemporary", "Future")
TempFreq <- c(133, 581, 115)

MoserEkSJ <- cbind(SJCat, SJFreq)
rownames(MoserEkSJ) <- MoserEkSJ[, 1]
MoserEkSJ <- as.data.frame(MoserEkSJ)


ggplot(MoserEkSJ, aes(y=SJFreq, x=SJCat)) + 
    geom_bar(stat="identity", position="dodge", fill="#5C8C4C")+ 
  ggtitle("Spatial/Jurisdictional Type of Reported Barriers to Wetland Restoration") +
  xlab("Spatial/Jurisdictional Barrier Type") + ylab("Frequency")+ geom_text(aes(label = SJFreq), size = 3, hjust = 2) + coord_flip()

MoserEkSJ$SJFreq <-as.numeric(MoserEkSJ$SJFreq)
MoserEkSJ$Origin <- MoserEkSJ$SJCat
MoserEkSJ$labels <- c("Proximate (439) 53%", "Remote (390) 47%")
sjcatcolors <- c("#d9b99b", "#fff0db")

ggplot(MoserEkSJ, aes(x =2, y = SJFreq, fill = Origin)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y", start=0)+
  scale_fill_manual(values=sjcatcolors)+
  geom_text(aes(label = labels), position = position_stack(vjust = 0.5), color="black")+
  theme_void() + # Removes the axes and background
    xlim(0.5, 2.5) +
  labs(title = "Spatial/Jurisdictional Barrier Origins (N=829)")

MoserEkT <- cbind(TempCat, TempFreq)
rownames(MoserEkT) <- MoserEkT[, 1]
MoserEkT <- as.data.frame(MoserEkT)

MoserEkT$TempFreq <-as.numeric(MoserEkT$TempFreq)
MoserEkT$Origin <- MoserEkT$TempCat
MoserEkT$labels <- c("Legacy (133) 16%", "Contemporary (581) 70%", "Future (115) 14%")
Tcatcolors <- c("#d9b99b", "#fff0db", "#834333")

ggplot(MoserEkT, aes(x =2, y = TempFreq, fill = Origin)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y", start=0)+
  scale_fill_manual(values=Tcatcolors)+
  geom_text(aes(label = labels), position = position_stack(vjust = 0.5), color="black")+
  theme_void() + # Removes the axes and background
    xlim(0.5, 2.5) +
  labs(title = "Temporal Barrier Origins (N=829)")

ggplot(MoserEkT, aes(y=TempFreq, x=TempCat)) + 
    geom_bar(stat="identity", position="dodge", fill="#5C8C4C")+ 
  ggtitle("Temporality of Reported Barriers to Wetland Restoration") +
  xlab("Temporal Barrier Type") + ylab("Frequency")+ geom_text(aes(label = TempFreq), size = 3, hjust = 2) + coord_flip()



```

```{r Moser Ekstrom barriers by project and staff}
MoEkProjStaff <- barriers %>% select(c(FinRole, FinProject, spatialorigin, temporigin))

MoEkStaffTCT <- as.data.frame(table(MoEkProjStaff$FinRole, MoEkProjStaff$temporigin))
MoEkStaffSJCT <- as.data.frame(table(MoEkProjStaff$FinRole, MoEkProjStaff$spatialorigin))

MoEkProjTCT <- as.data.frame(table(MoEkProjStaff$FinProject, MoEkProjStaff$temporigin))
MoEkProjSJCT <- as.data.frame(table(MoEkProjStaff$FinProject, MoEkProjStaff$spatialorigin))

####Update these and then reimport##--------NEED TO FIX
staffTchisq <- read.csv("StaffTempB.csv", sep=';')
staffSJchisq <- read.csv("StaffSpatialBs.csv", sep=';')

projTchisq <- read.csv("ProjTempB.csv", sep=';')
projSJchisq <- read.csv("ProjSpatialBs.csv", sep=';')

rownames(staffTchisq) <- staffTchisq$X
staffTchisq <- staffTchisq[, -1]
chisq.test(staffTchisq)$expected #expected count over 5 for all (lowest is 13.9)
Tstaffchi_result <- chisq.test(staffTchisq)
print(Tstaffchi_result)


rownames(staffSJchisq) <- staffSJchisq$X
staffSJchisq <- staffSJchisq[, -1]
chisq.test(staffSJchisq)$expected #all above 5 expected count 
SJstaffchi_result <- chisq.test(staffSJchisq)
print(SJstaffchi_result)

rownames(projSJchisq) <- projSJchisq$X
projSJchisq <- projSJchisq[, -1]
chisq.test(projSJchisq)$expected #expected counts minimum is 8.9, use regular
projSJchitest <- chisq.test(projSJchisq)
projSJchitest


rownames(projTchisq) <- projTchisq$X
projTchisq <- projTchisq[, -1]
chisq.test(projTchisq)$expected #expected counts minimum is 2.6, use fisher's
projTfishtest <- fisher.test(projTchisq, simulate.p.value = TRUE)
projTfishtest


moserekCT <- as.data.frame(table(MoEkProjStaff$spatialorigin, MoEkProjStaff$temporigin))

moserekchisq.prox <- c(67, 316, 56)
moserekchisq.rem <- c(66, 265, 59)
moserekchisq <- as.data.frame(rbind(moserekchisq.prox, moserekchisq.rem))
rownames(moserekchisq) <- c("Proximate", "Remote")
colnames(moserekchisq) <- c("Legacy", "Contemporary", "Future")
chisq.test(moserekchisq)$expected #all cell counts >5 expected
mosekchi_result <- chisq.test(moserekchisq)
print(mosekchi_result)


```

```{r sankey diagram}

#code from: https://rpubs.com/oomiwale1/926103
 
#install.packages("devtools")
#devtools::install_github("davidsjoberg/ggsankey")

library(ggsankey)

table(barriers$spatialorigin, barriers$Barrier)
table(barriers$temporigin, barriers$Barrier)
table(barriers$spatialorigin, barriers$temporigin)

sankeydata <- barriers %>% select(Barrier, spatialorigin, temporigin)
colnames(sankeydata) <- c("Barrier", "SpatialOrigin", "TemporalOrigin")
sankeydata <- sankeydata %>%
  make_long(Barrier, SpatialOrigin, TemporalOrigin)

reagg <- sankeydata%>%
  dplyr::group_by(node)%>%  # Here we are grouping the data by node and then we are taking the frequency of it 
  tally()

sankeydata2 <- merge(sankeydata,
             reagg, 
             by.x = 'node', 
             by.y = 'node', 
             all.x = TRUE)

skpl <- ggplot(sankeydata2, aes(x = x,                        
                     next_x = next_x,                                     
                     node = node,
                     next_node = next_node,        
                     fill = factor(node),
                     label = paste0(node, " = ", n)))             # This Creates a label for each node
                     
skpl <- skpl +geom_sankey(flow.alpha = 0.5,          #This Creates the transparency of your node 
                      node.color = "black",     # This is your node color        
                      show.legend = TRUE)        # This determines if you want your legend to show

skpl <- skpl + geom_sankey_label(size = 2,
                             color = "black", 
                             fill = "white") # This specifies the Label format for each node 

skpl <- skpl + theme_bw()
skpl <- skpl + theme(legend.position = 'none')
skpl <- skpl + theme(axis.title = element_blank(),
                 axis.text.y = element_blank(),
                 axis.ticks = element_blank(),
                 panel.grid = element_blank())


skpl <- skpl + scale_fill_viridis_d(option = "inferno")
skpl <- skpl + labs(title = "Sankey Diagram of Barriers")
skpl <- skpl + labs(subtitle = "From Interviews (N=829)")
skpl <- skpl + labs(fill = 'Nodes')

skpl <- skpl + scale_fill_manual(values = c('Remote' = "chocolate4",
                                        'Proximate' = "chocolate2",
                                        'Social' = "#5C8C54",
                                        'Resource' = "#C2B15B",
                                        'Phys/Enviro' = "#341C02",
                                        'Institutional' = "#a95c10",
                                        'Informational' = "#fff0db",
                                        'Cognitive' = "#55B458",
                                        'Legacy'="#834333",
                                        'Contemporary'="#d9b99b",
                                        'Future'="#fff8e7"))

skpl

```